добавляет сетку главной страницы и крупных блоков
htmlacademy-htmlcss/1954051-sedona-34 pull request #5
Opened 2022-06-15 14:43 UTC by d7add9

нужен code-review, т.к. я немного подвис на задании и не понимаю до конца, в правильном ли направлении двигаюсь в задании

2022-06-17 11:53 UTC, Pakistanka requested changes

2022-06-17 11:53 UTC, Pakistanka commented on styles/styles.css
> +display: flex;
форматирование нарушил немного.

И в footer не увидела сетки http://joxi.ru/p27Yw3pTLV5Vdr

2022-06-17 11:53 UTC, Pakistanka commented on styles/styles.css
> +width: 720px;
Форматирование

2022-06-18 05:09 UTC, d7add9 commented on styles/styles.css
> +display: flex;
хм. у меня вот этот flex, заданный для page-footer-container показывается так на обеих страницах проекта в firefox и chrome. https://www.dropbox.com/s/rp7a939d6h6jumm/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202022-06-18%20%D0%B2%2007.58.28.png?dl=0 
а в safari вот так https://www.dropbox.com/s/43wxo964bsszh1n/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202022-06-18%20%D0%B2%2008.07.21.png?dl=0 
соответственно вопрос: почему это может происходить, и что нужно поправить в сетке (если нужно), если ты не имела в виду добавление сетки для элементов внутри частей футера (расставить соц. сети по ней, например - это вроде в следующем задании нужно)

2022-06-19 16:24 UTC, Pakistanka commented on styles/styles.css
> +display: flex;
Я имела именно добавление сетки внутри

2022-06-19 17:47 UTC, Pakistanka requested changes

2022-06-19 17:47 UTC, Pakistanka commented on catalog.html
> +            <a href="#" class="button button-selected">
Мы с тобой обсуждали, что у тега - a, не может быть класса button (что значит "кнопка")

2022-06-19 17:47 UTC, Pakistanka commented on catalog.html
> +          <span class="button-name">Подписаться</span>
Этот span избыточен
`<button class="button button-additional newsletter-button" type="submit">Подписаться</button>`

Должно быть вот так

2022-06-19 17:47 UTC, Pakistanka commented on catalog.html
> +                <a class="button" href="https://vk.com/htmlacademy">
Ошибка с ссылкой и классом - кнопка

2022-06-19 17:47 UTC, Pakistanka commented on catalog.html
> +            <a href="https://htmlacademy.ru/"> <img src="images/logo-htmlacademy.svg" width="115" height="34"
Нарушено форматирование

2022-06-19 17:47 UTC, Pakistanka commented on index.html
> +            <span class="button-name">Подписаться</span>
span избыточен, см. выше

2022-06-19 17:47 UTC, Pakistanka commented on styles/styles.css
> +  margin: 0% auto;
Нелогичное свойство

2022-06-19 17:47 UTC, Pakistanka commented on catalog.html
> +        <div class="page-footer-container">
Зачем эта обертка?

Она избыточна, у тебя же есть еще footer

2022-06-19 17:47 UTC, Pakistanka commented on index.html
> +          <form class="newsletter-form" action="https://echo.htmlacademy.ru" method="post"></form>
Последующие label, input and button должны лежать внутри тега form, а они у тебя на одном уровне

2022-06-19 17:47 UTC, Pakistanka commented on index.html
> +                <img class="advantages-image-1" src="images/sedona-1.jpg" width="800" height="384" alt="Фото Седоны.">
Нельзя вкладывать картинку внутрь тега - p, так как параграф оборачивает только текст

2022-06-19 17:47 UTC, Pakistanka commented on index.html
> +            <li class="advantages-item advantages-item-illustrated">
Для advantages-item-illustrated потерян display: flex

2022-06-19 17:47 UTC, Pakistanka commented on index.html
> +                <img class="advantages-image-2" src="images/sedona-2.jpg" width="800" height="384"
Нельзя картинку вкладывать в тег p

2022-06-19 18:13 UTC, d7add9 commented on styles/styles.css
> +  margin: 0% auto;
расшифруй, в чем именно нелогичность. в самом наличии этого свойства, или в его содержимом?

2022-06-19 18:14 UTC, d7add9 commented on catalog.html
> +        <div class="page-footer-container">
т.е. лучше задать flex классу page-footer а див убрать?

2022-06-20 07:31 UTC, Pakistanka commented on styles/styles.css
> +  margin: 0% auto;
Отступ в 0% - очень странно.

Если хочешь просто отцентровать, то лучше 0px поставить

2022-06-20 07:31 UTC, Pakistanka commented on catalog.html
> +        <div class="page-footer-container">
Да

2022-06-20 16:44 UTC, d7add9 commented on styles/styles.css
> +  margin: 0% auto;
в тренажерах было вот так - "
Чтобы отцентровать блочный элемент, нужно выполнить следующие действия:

Задать элементу ширину, которая меньше ширины родительского контейнера.
Задать для внешних отступов справа и слева значение auto.
Примеры кода:

selector {
  width: 100px;
  margin: 0 auto;
}

selector {
  width: 100px;
  margin-left: auto;
  margin-right: auto;
} "

я в любом случае удалил этот лишний div и указал центрирование уже для класса самого футера

2022-06-20 18:45 UTC, Pakistanka commented on styles/styles.css
> +  margin: 0% auto;
Ну так `margin: 0 auto;`. Про проценты здесь ни слова не написано

2022-06-20 18:47 UTC, merged